### PR TITLE
French Translation

### PR DESCRIPTION
**Pull request by FlorianKempenich**
Hi,

You extension totally made my day when I found out about it, when I realized you were looking for translation I couldn't resist the opportunity to contribute. 

I'm a French native speaker but haven't lived in the country for quite some of time. For that reason I haven't really written any official documentation in French in ages. I tried my best to translate, but gramatical errors might have sneaked in. Can't promise perfect, but it's good enough that a French person not speaking a word of english would understand everything . . . though they'd still need english to _use PlantUML itelf_ 😁

### Translations to review
Here are a couple of translations I wasn't sure about.
#### `package.nls.fr.json`
* `plantuml.configuration.exportMapFile`: _"Determine whether export image map (.cmapx) file when export."_
  * Even after some research I still couldn't figure out what this option was supposed to do.
  * I left the English version in the French translation
  * **Could you help me understand so that I can try to phrase it in French?**
  * **Or would you rather keep the English version for this particular option rather than risking a possible mis-translation?**
* `plantuml.configuration.exportConcurrency`: _"Decides concurrency count when export multiple diagrams."_
  * I took the liberty of rephrasing it for the French version, as the original version didn't make much sense with French syntax.
  * The French version is: _"Nombres de threads à utiliser lors de l'exportation de plusieurs diagrammes en parallele"_  
    Which literally means: _"Number of threads to use when exporting multiple diagrams in parallel"_
  * **Are you ok with that translation?**

* **Other translations:** Overall I took some liberties to make the translations sound correct according to French grammar and culture. I did not however changed the meaning of any of them besides the one mentionned above (or at least not knowingly). That being said I encourage you to use Google translate to revert all translations to English and ask me questions if you're not sure about a particular formulation ;)

### CODE REVIEW

**Comment by FlorianKempenich** [comment]
Oh well, look what I noticed seconds after submitting this PR: 
* _[Translate lang.nls.json and package.nls.json to french #191](#191)_

Well @Zepmanbc, more perspectives will only bring a more refined version of the translation. I'm not sure how cases like these are usually handled, can you think of a way to properly merge the 2 translations? @qjebbs ?
The idea isn't to turn this into a headache, if it's not easily done I don't mind closing this PR and simply using @Zepmanbc version 😉

**Comment by qjebbs** [comment]
Thanks for your contribution! 

I don't know French at all, but I believe both of the translations (#191, #193) have their better part. So a reasonable choice could be:

1. I merge the first PR
2. If you have better translations, please  start a PR based on previous one.

It's a way that two PRs to be merged. What do you think?

---

Here is my reply to your Questions:

- `(.cmapx) file`: used to describe hot zone of links of the export image, if you put links in diagrams.
- `exportConcurrency`, local render starts one process for each diagram export, concurrency defines how many processes to start at a time. More processes many accelerate the export, but not always, related to your PC hardware. Your FR translation seems good.

**Comment by FlorianKempenich** [comment]
I think it's a good solution :) 
I'll look into it now

**Comment by FlorianKempenich** [comment]
Hi @qjebbs @Zepmanbc

All done 🙂 
I merged @Zepmanbc translation with mine

I spent quite some time working on my original translation and really tried to make things sound as natural as possible. I was pleasantly surprised to see some translations from @Zepmanbc breaching that barrier in ways I hadn't even thought of. 😃
For some other translations I found my version easier to understand, I replaced the translation in these cases.

To @Zepmanbc:
"Easier to understand" being highly dependent on each and everyone's perspective, I'd really like if you could review my modifications, and tell me if you agree with the changes, would like to amend some, or roll back some other 😉

Thanks both of you for the great work!

**Comment by Zepmanbc** [comment]
Great work, ok for me 👍

**Comment by FlorianKempenich** [comment]
Awesome 🙂

**Comment by qjebbs** [comment]
Many thanks!

**Pull request merged**
