### PR TITLE
Support syntax highlighting of functions and fields with accents

### PR DESCRIPTION
**Pull request by fuhrmanator**
For example, recognize the field `activé` in a class:

class A {
    activé : Boolean
}

### CODE REVIEW

**Comment by qjebbs** [comment]
I suggest you replace `[0-9a-zA-Z_]+` with `(?:\w|_)+`

**Comment by fuhrmanator** [comment]
> I suggest you replace `[0-9a-zA-Z_]+` with `\S+`. If characters other than `ascii` is allowed, then allow all, not some of them

OK - the scope of my PR was to allow accented characters (incremental improvement), but I suppose this could also include any valid characters. It's pretty ambitious since UTF has a lot of possibilities (Voltaire said the best is the enemy of good).

I am not good with .yaml-tmLanguage syntax. Is there a documentation for how it works in VSCode? How can I define a reg-ex variables for things like identifiers? I found http://www.sublimetext.com/docs/3/syntax.html which has a `variables:` section, but I am not sure it's compatible with what the project will use.

**Comment by qjebbs** [comment]
@fuhrmanator Agree with you. I firstly want to change to `\w`, but the JS `RegExp` behaviors different with other languages.

Within this project, you can run `npm run buildsyntax` to convert `diagram.yaml-tmLanguage` to `diagram.tmLanguage`.

**Comment by fuhrmanator** [comment]
I think I solved it with `\p{L}`, but I wasn't sure my tests are accurate. I'm on windows 10 with `npm`  in bash.

**Comment by fuhrmanator** [comment]
See https://rubular.com/r/9p7JpPGAJtcGFJ and https://rubular.com/r/cJ15lkb8dcSGvK for tests -- I checked with my extension and it seems to work well.

**Comment by fuhrmanator** [comment]
Also, I could not get the `variables:` definition to work, at least not the way it's documented in http://www.sublimetext.com/docs/3/syntax.html#variables -- I suppose `.yaml-tmLanguage` is not really the same format?

**Comment by qjebbs** [comment]
I  can confirm that `[\p{L}0-9_]+` works, when it replace `[0-9a-zA-Z_]+`. And please squash commits into one commit, before I can merge.

`.yaml-tmLanguage` should finally convert to `.tmLanguage`, before it can be used. I don't know how well VSCode implemented (like the `variables` you said) according to the `sumlime` documentations.

**Comment by fuhrmanator** [comment]
> please squash commits into one commit, before I can merge.

GitHub will squash for you on the merge I think, if you choose the option. Is it ok?

https://stackoverflow.com/a/36377439/1168342

**Comment by qjebbs** [comment]
OK, thanks for all your work!

**Pull request merged**
