### PR TITLE
Refactored to make adding keywords easier, fixes #333

### LINKED ISSUE #333: Support more predefined words on skinparam
There are some missing predefined words, but I'm not sure where to add them in a PR: 

> skinparam style **strictuml**
> skinparam handwritten **true**
> skinparam ObjectAttributeFontStyle **normal**

For boolean, there is also **false**.
For font styles, there are **italic**, **bold** and **plain**.

I think these keywords are similar to **left**, **right**, **center** which are alignment keywords on skinparam. There are probably more to add; I didn't do a thorough search.

### PR DESCRIPTION
**Pull request by fuhrmanator**
Hope you don't mind the refactor - it should make it easier to maintain these.

### CODE REVIEW

**Comment by qjebbs** [comment]
You know what, I keep the keywords in a string, because it's compatible (and same process) to dealing with output of `java -jar plantuml.jar -language`, in this way, we prompt keywords only current jar supports.

For some reason, I temporary remove this logic, but I may improve and bring it back some day.

https://github.com/qjebbs/vscode-plantuml/blob/26041d7d55b95423a73fc76b0152457903f6e3dd/src/plantuml/intellisense/languageCompletion.ts#L21-L44

So to fix the issue, the simplest way is replacing `preDefinedWords` with latest output of `java -jar plantuml.jar -language`

**Comment by fuhrmanator** [comment]
There is still a problem then with #333 - many of those words don't show up in the latest list (strictuml, italic, bold, circle, description, ...). Perhaps there's a way to merge the two methods?

**Comment by fuhrmanator** [comment]
Or maybe we can pressure PlantUML maintainer to update that list (upstream bug).

**Comment by qjebbs** [comment]
May I suggest you add missing keyword manually, and comment with "Don't replace this with plantuml.jar output" or something? Until the upstream bug is resolved.

**Comment by fuhrmanator** [comment]
> May I suggest you add missing keyword manually, and comment with "Don't replace this with plantuml.jar output" or something? Until the upstream bug is resolved.

It's been resolved for the short term (but could occur again, because when a new keyword is added, it must be also added to a list of keywords). See the discussion at https://github.com/plantuml/plantuml/issues/359

I think it's better to depend on the content of https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/syntax/LanguageDescriptor.java rather than reproducing the keywords here.

**Comment by qjebbs** [comment]
The point is, I cannot trace the language changes all the time. PlantUML project have more people and keywords comes from them. If the upstream can miss some keywords, how can anyone expect me alone to do better than them, to not miss something.

Now that upstream provides a keywords command, my best choice is to depend on it.

Since we are digging this so deep, I could say, we can use both custom keywords array and generating. We merge two sets of keywords with program logic, so that we can do something on both ends when this issue occurs.

**Pull request closed without merging**
