### PR TITLE
Please update plugin with latest from https://github.com/qjebbs/vscode-plantuml

### PR DESCRIPTION
**Pull request by c835722**
Thank you for this plugin. Its works well for me (when I run it in with all other plugins disabled).
There is a bug (that was fixed recently) in the base plugin that prevents the plugin failing (which is what this plugin is currently doing for me when other plugins are enabled)
Could you please update this version to pull the fix from https://github.com/qjebbs/vscode-plantuml/issues/68 commit https://github.com/qjebbs/vscode-plantuml/commit/247c84ddd94061608c768809a4c44468c3facf10.
Cheers.

### CODE REVIEW

**Comment by c835722** [comment]
Sorry. That didnt quite work out as I expected.
I wanted the fork to be updated from the base.
Will try to undo this confusion.

**Comment by c835722** [comment]
Sorry that didnt quite work out as expected.
I wanted the fork updated not the base as it already has the change.

**Comment by c835722** [comment]
It appears the forked repo does not allow issues.
@jkeys089 could you consider pulling this change to your fork.

**Comment by c835722** [comment]
Thanks @jkeys089 . I assume there is some lag now where the vs-code marketplace pulls and builds your change before it is published and available to a user given an uninstall and re-install of the plugin does not yet contain the change ...

**Comment by jkeys089** [comment]
@c835722 after fighting a bit with typescript and vsce I finally was able to publish an updated version with this fix. Thanks for pointing it out!

**Comment by c835722** [comment]
Thank you @jkeys089 .

**Pull request closed without merging**
